### ISSUE TITLE
Elasticsearch Timeouts

### ISSUE THREAD

**Issue by nigelbabu** [okfn/foundation#248]
It turns out that adding press releases is causing Elasticsearch Timeouts. Check if it was transient or not with some testing on staging.
```
Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/reversion/revisions.py", line 297, in do_revision_context
    return func(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1164, in add_view
    self.save_model(request, new_object, form, False)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 893, in save_model
    obj.save()

  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)

  File "/app/.heroku/python/lib/python2.7/site-packages/haystack/signals.py", line 48, in handle_save
    index.update_object(instance, using=using)

  File "/app/.heroku/python/lib/python2.7/site-packages/haystack/indexes.py", line 277, in update_object
    backend.update(self, [instance])

  File "/app/.heroku/python/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 187, in update
    bulk_index(self.conn, prepped_docs, index=self.index_name, doc_type='modelresult')

  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 176, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):

  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 118, in streaming_bulk
    raise e

ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPSConnectionPool(host='fig-1642833.us-east-1.bonsai.io', port=443): Read timed out. (read timeout=10))
```

**Comment by nigelbabu** [comment]
Fixed up with an index rebuild.
