### ISSUE TITLE
Elasticsearch Error

### ISSUE THREAD

**Issue by nigelbabu** [okfn/foundation#249]
Another error from Elasticsearch
```
Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/reversion/revisions.py", line 297, in do_revision_context
    return func(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1164, in add_view
    self.save_model(request, new_object, form, False)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py", line 893, in save_model
    obj.save()

  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)

  File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)

  File "/app/.heroku/python/lib/python2.7/site-packages/haystack/signals.py", line 48, in handle_save
    index.update_object(instance, using=using)

  File "/app/.heroku/python/lib/python2.7/site-packages/haystack/indexes.py", line 277, in update_object
    backend.update(self, [instance])

  File "/app/.heroku/python/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 190, in update
    self.conn.indices.refresh(index=self.index_name)

  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)

  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 53, in refresh
    params=params)

  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)

  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 86, in perform_request
    self._raise_error(response.status, raw_data)

  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 102, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

AuthorizationException: TransportError(403, u'IndexClosedException[[foundation] closed]')
```

**Comment by nigelbabu** [comment]
Fixed up with an index rebuild.
